// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrzelicznikWPF.Model.BazaDanych.Model;

namespace PrzelicznikWPF.Model.BazaDanych.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20220523102022_utworzenieMigracji")]
    partial class utworzenieMigracji
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("PrzelicznikWPF.Model.BazaDanych.Model.Jednostki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<int>("RodzajId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RodzajId");

                    b.ToTable("Jednostki");
                });

            modelBuilder.Entity("PrzelicznikWPF.Model.BazaDanych.Model.Przeliczniki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JednostkaDocelowaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JednostkaZrodlowaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Wartosc")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("JednostkaDocelowaId");

                    b.HasIndex("JednostkaZrodlowaId");

                    b.ToTable("Przeliczniki");
                });

            modelBuilder.Entity("PrzelicznikWPF.Model.BazaDanych.Model.Rodzaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rodzaj");
                });

            modelBuilder.Entity("PrzelicznikWPF.Model.BazaDanych.Model.Jednostki", b =>
                {
                    b.HasOne("PrzelicznikWPF.Model.BazaDanych.Model.Rodzaj", "Rodzaj")
                        .WithMany()
                        .HasForeignKey("RodzajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rodzaj");
                });

            modelBuilder.Entity("PrzelicznikWPF.Model.BazaDanych.Model.Przeliczniki", b =>
                {
                    b.HasOne("PrzelicznikWPF.Model.BazaDanych.Model.Jednostki", "JednostkaDocelowa")
                        .WithMany()
                        .HasForeignKey("JednostkaDocelowaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrzelicznikWPF.Model.BazaDanych.Model.Jednostki", "JednostkaZrodlowa")
                        .WithMany()
                        .HasForeignKey("JednostkaZrodlowaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JednostkaDocelowa");

                    b.Navigation("JednostkaZrodlowa");
                });
#pragma warning restore 612, 618
        }
    }
}
